<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PowerTools</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Compile Remove="PowerTools.Desktop\**\*.cs" />
    <Content Remove="tests\**\*" />
    <Content Remove="PowerTools.Desktop\**\*" />
    <Content Remove="artifacts\**\*" />
    <Content Remove="publish\**\*" />
    <None Remove="tests\**\*" />
    <None Remove="PowerTools.Desktop\**\*" />
    <None Remove="artifacts\**\*" />
    <None Remove="publish\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AnalysisServices" Version="19.114.12" />
    <PackageReference Include="Microsoft.AnalysisServices.AdomdClient" Version="19.114.12" />
  </ItemGroup>
</Project>
